// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type ScribbleCategory struct {
	DocID    int64
	Category string
}

type ScribbleContent struct {
	ID  int64
	Doc string
}
