// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sqlite.sql

package db

import (
	"context"
)

const deleteDocumentBySlug = `-- name: DeleteDocumentBySlug :exec
DELETE FROM scribble_content WHERE json_extract(doc, '$.properties.slug') = json_array(cast(?1 as text))
`

func (q *Queries) DeleteDocumentBySlug(ctx context.Context, slug string) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentBySlug, slug)
	return err
}

const docExistsBySlug = `-- name: DocExistsBySlug :one
SELECT EXISTS (
    SELECT 1 FROM scribble_content 
        WHERE json_extract(doc, '$.properties.slug') = json_array(cast(?1 as text)) 
        LIMIT 1
)
`

func (q *Queries) DocExistsBySlug(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, docExistsBySlug, slug)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getDocumentBySlug = `-- name: GetDocumentBySlug :one
SELECT doc FROM scribble_content 
    WHERE json_extract(doc, '$.properties.slug') = json_array(cast(?1 as text)) 
    LIMIT 1
`

func (q *Queries) GetDocumentBySlug(ctx context.Context, slug string) (string, error) {
	row := q.db.QueryRowContext(ctx, getDocumentBySlug, slug)
	var doc string
	err := row.Scan(&doc)
	return doc, err
}

const insertDocument = `-- name: InsertDocument :exec
INSERT INTO scribble_content (doc) VALUES (?)
`

func (q *Queries) InsertDocument(ctx context.Context, doc string) error {
	_, err := q.db.ExecContext(ctx, insertDocument, doc)
	return err
}

const listCategories = `-- name: ListCategories :many
SELECT DISTINCT category FROM scribble_categories 
    ORDER BY category ASC 
    LIMIT ? OFFSET ?
`

type ListCategoriesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCategories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesLike = `-- name: ListCategoriesLike :many
SELECT DISTINCT category FROM scribble_categories 
    WHERE category LIKE ?
    ORDER BY category ASC 
    LIMIT ? OFFSET ?
`

type ListCategoriesLikeParams struct {
	Category string
	Limit    int64
	Offset   int64
}

func (q *Queries) ListCategoriesLike(ctx context.Context, arg ListCategoriesLikeParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesLike, arg.Category, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT doc FROM scribble_content 
    ORDER BY json_extract(doc, '$.properties.created_at') DESC 
    LIMIT ? OFFSET ?
`

type ListDocumentsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var doc string
		if err := rows.Scan(&doc); err != nil {
			return nil, err
		}
		items = append(items, doc)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByCategory = `-- name: ListDocumentsByCategory :many
SELECT sc.doc FROM scribble_content sc
    JOIN scribble_categories c ON sc.id = c.doc_id
    WHERE c.category = ?
    ORDER BY json_extract(sc.doc, '$.properties.created_at') DESC 
    LIMIT ? OFFSET ?
`

type ListDocumentsByCategoryParams struct {
	Category string
	Limit    int64
	Offset   int64
}

func (q *Queries) ListDocumentsByCategory(ctx context.Context, arg ListDocumentsByCategoryParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsByCategory, arg.Category, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var doc string
		if err := rows.Scan(&doc); err != nil {
			return nil, err
		}
		items = append(items, doc)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentBySlug = `-- name: UpdateDocumentBySlug :exec
UPDATE scribble_content 
    SET doc = ? 
    WHERE json_extract(doc, '$.properties.slug') = json_array(cast(? as text))
`

type UpdateDocumentBySlugParams struct {
	Doc  string
	Slug string
}

func (q *Queries) UpdateDocumentBySlug(ctx context.Context, arg UpdateDocumentBySlugParams) error {
	_, err := q.db.ExecContext(ctx, updateDocumentBySlug, arg.Doc, arg.Slug)
	return err
}
